<?php
?>
<main id="connexion">

    <section class="centre">
        <h1>Connexion</h1>
        <article>
            <h2>Entres tes identifiants</h2>
            <?php
            if ($member->isIdentify() == true): ?>
                    <p>Vous êtes déjà connecté.</p>
                </article>
                </section>
            <?php
                die();
                endif;
            ?>
            <div>
                <ul class="flex flex-column error">
                    <li><?php echo $errorConnexion; ?></li>
                    <li><?php echo $errorLogin; ?></li>
                    <li><?php echo $errorPassword; ?></li>
                </ul>
            </div>


            <form action="connecting" method="post">

                <div class="flex flex-column">
                    <label for="login" class="outOfScreen">login:</label>
                    <input type="text" name="login" id="login" placeholder="Login"/>
                </div>
                <div class="flex flex-column marge-top">
                    <label for="password" class="outOfScreen">Mot de passe:</label>
                    <input type="password" name="password" id="password" placeholder="Mot de passe"/>
                </div>

                <input type="submit" class="button" value="Connexion"/>
            </form>


            <div>
                <a href="inscription" class="button">Pas de compte ?</a>
                <a href="forgotPassword" class="button">Mot de passe oublié ?</a>
            </div>
        </article>
    </section>
</main>