<?php
?>

<main>
    <h1>Mots de passe oublié</h1>
    <section>
        <article>
            <p>Merci de renseigner l'un des champs suivant.</p>
            <form>
                <label FOR="login">Login</label>
                <input type="text" name="login" id="login" placeholder="Votre login">

                <label FOR="mailAdress">Adresse mail</label>
                <input type="email" name="mailAdress" id="mailAdress" placeholder="votre adresse mail">

                <input type="submit" value="Envoyer" id="submitButton">
            </form>
        </article>
    </section>

    <div id="answer"></div>
</main>
<script src="<?php echo JS_URL;?>/forgotPassword/functions.js"></script>
<script src="<?php echo JS_URL;?>/forgotPassword/main.js"></script>